# Nombre y clave del proyecto
sonar.projectKey=udeverso-react-server
sonar.projectName=udeverso-react-server

# Lenguaje principal
sonar.language=js

# Fuente y pruebas
sonar.sources=server/src, client/src
sonar.tests=server/tests

# Cobertura de pruebas
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info

# Configuración de la versión de SonarQube y servidor
sonar.host.url=http://localhost:9000
sonar.login=squ_0ed33d8580bdc77c338236b67cf1ec36cf4a804b