/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/items/Pizarron.glb --transform 
Files: public/models/items/Pizarron.glb [14.44KB] > /home/valentinalopez/Development/udeverso-react/client/Pizarron-transformed.glb [8.38KB] (42%)
*/

import React, { useRef, useContext } from "react";
import { useGLTF } from "@react-three/drei";
import { VideoScreen } from "./Streaming/VideoScreen";
import { Environment, OrbitControls, Html } from "@react-three/drei";
import { RoomContext } from "../context/RoomContext";
import { UserContext } from "../context/UserContext";

export function Pizarron(props) {
  const { nodes, materials } = useGLTF(
    "/models/items/Pizarron-transformed.glb"
  );
  const { screenStream, peers, screenSharingId } = useContext(RoomContext);
  const { userId } = useContext(UserContext);

  const screenSharingVideo =
    screenSharingId === userId ? screenStream : peers[screenSharingId]?.stream;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials["Material #45"]}
        position={[-4.854, 2.798, -1.338]}
        rotation={[Math.PI / 2, 0, -3.122]}
        scale={[0.009, 0.01, 0.009]}
      />
      <group
        position={[-4.889, 0.798, 0.429]}
        rotation={[-Math.PI, 0.02, -Math.PI]}
        scale={[0.008, 0.02, 0.022]}
      >
        <mesh
          geometry={nodes.Malla003.geometry}
          material={materials["01 - Default"]}
        />
        <mesh
          geometry={nodes.Malla003_1.geometry}
          material={materials["02 - Default"]}
        />
        <mesh
          geometry={nodes.Malla003_2.geometry}
          material={materials["Material #59"]}
        ></mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/items/Pizarron-transformed.glb");
